import { Shield, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";

const Terms = () => {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border/50 bg-card/50 backdrop-blur sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Shield className="w-8 h-8 text-primary" />
            <span className="text-xl font-bold">Credit Repair AI</span>
          </div>
          <Button variant="ghost" asChild>
            <Link to="/">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Home
            </Link>
          </Button>
        </div>
      </header>

      <main className="container mx-auto px-4 py-12 max-w-4xl">
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Last updated: February 6, 2025</p>

        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8">
          <section>
            <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing or using Credit Repair AI ("the Service"), you agree to be bound by these Terms of Service. 
              If you do not agree to these terms, please do not use our Service. We reserve the right to modify these 
              terms at any time, and your continued use of the Service constitutes acceptance of any modifications.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
            <p className="text-muted-foreground leading-relaxed">
              Credit Repair AI provides AI-powered credit report analysis, dispute letter generation, and educational 
              resources to help users understand and improve their credit profiles. Our Service includes:
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2 text-muted-foreground">
              <li>Automated credit report analysis and error detection</li>
              <li>FCRA-compliant dispute letter generation</li>
              <li>Credit score tracking and simulation tools</li>
              <li>Educational resources about credit repair</li>
              <li>Deadline monitoring and notification systems</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">3. User Responsibilities</h2>
            <p className="text-muted-foreground leading-relaxed">You agree to:</p>
            <ul className="list-disc pl-6 mt-4 space-y-2 text-muted-foreground">
              <li>Provide accurate and complete information when using the Service</li>
              <li>Maintain the confidentiality of your account credentials</li>
              <li>Use the Service only for lawful purposes</li>
              <li>Not misrepresent your identity or credit information</li>
              <li>Review and verify all generated dispute letters before submission</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">4. Legal Disclaimer</h2>
            <p className="text-muted-foreground leading-relaxed">
              <strong>Credit Repair AI is not a law firm and does not provide legal advice.</strong> The dispute letters 
              and recommendations generated by our Service are for informational purposes only. While our letters cite 
              relevant FCRA statutes (15 U.S.C. § 1681 et seq.), users are solely responsible for reviewing, customizing, 
              and submitting any correspondence to credit bureaus. We recommend consulting with a qualified attorney for 
              specific legal advice regarding your credit situation.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">5. No Guarantee of Results</h2>
            <p className="text-muted-foreground leading-relaxed">
              While our AI-powered tools are designed to identify potential errors and generate compliant dispute letters, 
              we cannot guarantee any specific outcomes. Credit bureau responses, item removals, and score improvements 
              depend on many factors beyond our control, including the accuracy of your credit report data and the 
              decisions of credit bureaus and furnishers.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">6. Intellectual Property</h2>
            <p className="text-muted-foreground leading-relaxed">
              All content, features, and functionality of the Service, including but not limited to text, graphics, 
              logos, and software, are owned by Credit Repair AI and protected by intellectual property laws. You may 
              not reproduce, distribute, or create derivative works without our express written permission.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">7. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, CREDIT REPAIR AI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, 
              SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, OR 
              GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">8. Account Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to suspend or terminate your account at any time for violations of these Terms of 
              Service or for any other reason at our sole discretion. Upon termination, your right to use the Service 
              will immediately cease.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">9. Governing Law</h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms of Service shall be governed by and construed in accordance with the laws of the United States, 
              without regard to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">10. Contact Information</h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have any questions about these Terms of Service, please contact us at support@creditrepairai.com.
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-border/50 py-8 mt-12">
        <div className="container mx-auto px-4 text-center text-muted-foreground">
          <p>&copy; {new Date().getFullYear()} Credit Repair AI. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

export default Terms;
